#Login Page Elements
txt_loginUserName = "name:Email"
txt_loginPassword = "name:Password"
btn_signIn = "xpath://button[@type='submit']"

#Employee General Info Page Elements
employment = "xpath://body/div[@class='kt-grid kt-grid--hor kt-grid--root']/div[@class='kt-grid__item kt-grid__item--fluid kt-grid kt-grid--ver kt-page']/div[@id='kt_wrapper']/div[@id='kt_header']/div[@class='kt-container']/div[@id='kt_header_menu_wrapper']/div[@id='kt_header_menu']/ul[@id='rf-nav']/li[@class='kt-menu__item kt-menu__item--submenu kt-menu__item--rel Employment']/a[@class='kt-menu__link kt-menu__toggle']/span[1]"
empgeneralinfo = "xpath://li[@class='kt-menu__item Employee_General_Info']//span[@id='rf-menu-text']"
btn_add = "xpath://span[normalize-space()='Add']"
empid = "id:EmployeeId"
fullname = "id:FullName"
fullnamebur = "id:FullNameBur"
dateofbirth = "id:BirthDate"
placeofbirth = "id:PlaceofBirth"
pname = "id:PreferredName"
bloodgroup = "xpath://span[contains(text(),'Blood Group')]"
gender = "xpath://span[@id='select2-GenderId-container']//span[@class='select2-selection__placeholder'][normalize-space()='Select an option']"
religion = "xpath://span[@id='select2-ReligionId-container']//span[@class='select2-selection__placeholder'][normalize-space()='Select an option']"
passport = "id:Passport"
passportexpirydate = "id:PassportExpireDate"
nrc = "id:NRCNo"
drivinglicense = "id:DrivingLicense"
maritalstatus = "id:select2-MaritalStatus-container"
ethnic = "id:select2-Ethnic-container"
fathername = "id:FatherName"
mothername = "id:MotherName"
nationality = "id:Nationality"
children = "id:NoofChildren"
depchildren = "id:NoofDependantChildren"
parentsalive = "id:NoofParentsAlive"

btn_save = "xpath://span[normalize-space()='Save']"
family = "xpath://div[@id='MaritalInfo']//i[contains(@class,'flaticon2-shelter')]"